### ISSUE TITLE
download from google drive folder - no weight .bin files

### ISSUE THREAD

**Issue by juldla** [SimonKitSangChu/pAbT5#1]
Hi, 

I wanted to run the inference step on the test example but ran into this issue FileNotFoundError: [Errno 2] No such file or directory: 'model_ckpt/pytorch_model-00001-of-00002.bin' -- I saw the bin files are lacking in the google drive folder. Could these be uploaded? 

Thanks in advance!

**Comment by SimonKitSangChu** [comment]
It should now be fixed. Let me know if you encounter other issues.
